/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdditionalContent: typeof import('./components/AdditionalContent/index.vue')['default']
    AdditionalContentSkeleton: typeof import('./components/AdditionalContentSkeleton/index.vue')['default']
    Article: typeof import('./components/Article/index.vue')['default']
    ArticleLink: typeof import('./components/ArticleLink/index.vue')['default']
    ArticleMedia: typeof import('./components/ArticleMedia/index.vue')['default']
    ArticlePhotos: typeof import('./components/ArticlePhotos/index.vue')['default']
    ArticleSkeleton: typeof import('./components/ArticleSkeleton/index.vue')['default']
    ArticleVideo: typeof import('./components/ArticleVideo/index.vue')['default']
    Comment: typeof import('./components/Comment/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconIonArrowBack: typeof import('~icons/ion/arrow-back')['default']
    IconIonArrowRedoOutline: typeof import('~icons/ion/arrow-redo-outline')['default']
    IconIonChatbubbleEllipsesOutline: typeof import('~icons/ion/chatbubble-ellipses-outline')['default']
    IconIonDuplicateOutline: typeof import('~icons/ion/duplicate-outline')['default']
    IconIonHeartOutline: typeof import('~icons/ion/heart-outline')['default']
    IconIonHomeOutline: typeof import('~icons/ion/home-outline')['default']
    IconIonSettingsOutline: typeof import('~icons/ion/settings-outline')['default']
    IconMajesticonsChevronDoubleDownLine: typeof import('~icons/majesticons/chevron-double-down-line')['default']
    IconMajesticonsThumbUpLine: typeof import('~icons/majesticons/thumb-up-line')['default']
    Loading: typeof import('./components/loading/index.vue')['default']
    MainContent: typeof import('./components/container/MainContent.vue')['default']
    RichTextInput: typeof import('./components/RichTextInput/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/container/Sidebar/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
